### ISSUE TITLE
Add a webpack chapter

### ISSUE THREAD

**Issue by damienbod** [AngularClass/awesome-angular2#123]
Some links to webpack would by useful.

https://webpack.github.io/

templates, seeds: 

https://github.com/AngularClass/awesome-angular2

https://github.com/damienbod/Angular2WebpackVisualStudio

https://github.com/preboot/angular2-webpack

https://github.com/schempy/angular2-typescript-webpack

**Comment by mgechev** [comment]
Would you open a PR with these?

**Comment by damienbod** [comment]
OK

**Comment by damienbod** [comment]
https://github.com/AngularClass/awesome-angular2/pull/124
