### ISSUE TITLE
Security chapter

### ISSUE THREAD

**Issue by damienbod** [AngularClass/awesome-angular2#125]
I think a security chapter would be useful:

https://damienbod.com/2016/03/02/angular2-openid-connect-implicit-flow-with-identityserver4/

https://github.com/michaeloryl/angular2-bootstrap4-oauth2-webpack

http://www.softwarearchitekt.at/post/2016/07/03/authentication-in-angular-2-with-oauth2-oidc-and-guards-for-the-newest-new-router-english-version.aspx

https://github.com/auth0-blog/angular2-authentication-sample

Should I create a PR? I'll add it at the end, ok?

greetings Damien

**Comment by gdi2290** [comment]
good idea, can you make a PR

**Comment by damienbod** [comment]
OK

**Comment by damienbod** [comment]
pull request: https://github.com/AngularClass/awesome-angular2/pull/126
