### ISSUE TITLE
more Babel content

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/awesome-angular2#15]
I would be great to have more Babel content

**Comment by shuhei** [comment]
Hi, now I'm creating a plunker for Babel + Angular 2 and it's almost done. What kind of content do you want to see?

**Comment by gdi2290** [comment]
can you include your angular 2 babel plugins to the list :+1:

**Comment by blacksonic** [comment]
Wrote about how to solve problems with Babel, but dont know where should i put it inside list?
https://medium.com/@blacksonic86/angular-2-dependency-injection-in-es6-f5551a3d6bf

**Comment by gdi2290** [comment]
@blacksonic add it to babel since you're using babel

**Comment by rolandjitsu** [comment]
I think there is plenty of Babel content now.
