### ISSUE TITLE
chore: fix urls

### ISSUE THREAD

**Issue by rolandjitsu** [AngularClass/awesome-angular2#163]
After integrating [awesome_bot](https://github.com/dkhamsing/awesome_bot) we got some urls that have some [issues](https://travis-ci.org/AngularClass/awesome-angular2/builds/172297971#L456).
We need to take care of them.

**Comment by vlio20** [comment]
@rolandjitsu, is this the reason why my PR are failing on travis? (https://github.com/AngularClass/awesome-angular2/pull/168)

**Comment by rolandjitsu** [comment]
@vlio20 yes, most likely. There are a bunch of urls that are either duplicates, moved or no longer exist.

**Comment by vlio20** [comment]
Is there a way to know which links? I would be happy to help with removing the broken links

**Comment by rolandjitsu** [comment]
@vlio20 yes, see [172297971#L456](https://travis-ci.org/AngularClass/awesome-angular2/builds/172297971#L456).
