### ISSUE TITLE
how install, how run this project ?

### ISSUE THREAD

**Issue by mlotfi2005** [AngularClass/awesome-angular2#189]
Hi,
I just cloned this code in my PC , started 

 npm install
npm WARN awesome-angular2@0.0.0 license should be a valid SPDX license expression

your help is appreciated.
thanks.

**Comment by rolandjitsu** [comment]
This repo is not a package that you can run, nor a starter. If you read carefully at the beginning of the repo:
```text
Awesome list of Angular 2 seed repos, starters, boilerplates, examples, tutorials, components, modules, videos, and anything else in the Angular 2 ecosystem
```

So it's pretty much just a document. If you are looking for a starter, there are many in this document that you can use.

I hope it's much clearer now :)
