### ISSUE TITLE
ionic in angular 2 ecosystem

### ISSUE THREAD

**Issue by gdi2290** [AngularClass/awesome-angular2#19]
Ionic is a platform but then it's kind of a collection of components but then it's a framework. How do we categorize Ionic 2? At the moment I have it under platform which really should be framework

cc @adamdbradley @mlynch

**Comment by rolandjitsu** [comment]
@gdi2290 by their definition it's a framework, so maybe it should be left to that. Also, I updated the url to the git repo for Ionic 2 and moved the section under Angular 2 in TypeScript as the entire ionic 2 codebase is in TypeScript.

And I think what's linked here and in awesome ionic2 should suffice for closing this issue.
