### ISSUE TITLE
some awesome new links...

### ISSUE THREAD

**Issue by born2net** [AngularClass/awesome-angular2#194]
some awesome new links...

Boilerplate now called Kitchen Sink:
https://github.com/born2net/Angular-kitchen-sink

adv ng video:
https://www.youtube.com/watch?v=vyiyJCLlGwo&feature=youtu.be

ng StoreModel for redux:
https://www.youtube.com/watch?v=bEkPEnudm7s&feature=youtu.be

ng seed Skeleton:
https://github.com/born2net/ng-skeleton

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by rolandjitsu** [comment]
If you'd like these links to be aded, please make a PR.
