### ISSUE TITLE
Cloudinary Angular2 SDK for image management

### ISSUE THREAD

**Issue by eitanp461** [AngularClass/awesome-angular2#200]
Thanks for this awesome list!

It was an excellent source of information when creating the new Cloudinary Angular SDK.

If you're not familiar with Cloudinary yet, it is an image and video SaaS solution for developers.

I've published a blog post describing the SDK and it would be great to have it featured here.

https://cloudinary.com/blog/new_angular_sdk_for_image_management_more_than_meets_the_eye

**Comment by rolandjitsu** [comment]
@eitanp461 Please make a PR with your addition and it will be merged in.
