### ISSUE TITLE
Broken link - TypeScript/Babel API Cheatsheet

### ISSUE THREAD

**Issue by m00s** [AngularClass/awesome-angular2#35]
The first item in the [cheatsheet list](https://github.com/AngularClass/awesome-angular2/blob/gh-pages/README.md#cheatsheet) is unreachable.

Since I never saw that cheatsheet I didn't remove the link, if anyone knows where to find it please fix it.

**Comment by gdi2290** [comment]
it's been moved to the website here
https://angular.io/cheatsheet

**Comment by gdi2290** [comment]
fixed via https://github.com/AngularClass/awesome-angular2/commit/16484331a4f98a5de31218eef1071671959c549a
