### ISSUE TITLE
Add ng2Boilerplate

### ISSUE THREAD

**Issue by born2net** [AngularClass/awesome-angular2#68]
please add http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

Regards,

Sean

**Comment by mgechev** [comment]
Would you open a PR?

**Comment by rolandjitsu** [comment]
@born2net made a pull request for this.

**Comment by born2net** [comment]
tx

**Comment by rolandjitsu** [comment]
@born2net no worries.

**Comment by valorkin** [comment]
@born2net nice one :)

**Comment by born2net** [comment]
tx :)

**Comment by born2net** [comment]
as I run into new and unique features / implementations  of ng2 features, I add them to ng2 boilerplate so it can be the ultimate kitchen sink!!!! to learn from and to bootstrap from as well...
