### ISSUE TITLE
Is the listed Angular2 IRC channel incorrect?

### ISSUE THREAD

**Issue by PaulCapestany** [AngularClass/awesome-angular2#74]
In the [community](https://github.com/AngularClass/awesome-angular2#community) section of the README, `#angular2` is listed as the "channel on Freenode IRC Server", yet there appears to be no active admin, and there's barely anyone in the room...

Just wondering if maybe there was a typo, or if most ng2 convo is expected to happen in `#angularjs`, or what?

**Comment by sunsevennv** [comment]
Good question - I am also trying to find an active IRC channel.

**Comment by haileyambition** [comment]
I am also seeking an active IRC channel

**Comment by thejoos** [comment]
Why don't we create a channel using Telegram.

**Comment by haileyambition** [comment]
Shouldn't make much difference where it is, but having people be active would be better.

**Comment by rolandjitsu** [comment]
@PaulCapestany the channel seems to be fine. So I will close this issue.

The fact that there is barely any activity there just means that you should probably look into using different channels of communication, such as Gitter where there is plenty of activity and the chances you will get some help are by far higher.
