### ISSUE TITLE
I formatted something wrong...

### ISSUE THREAD

**Issue by krimple** [AngularClass/awesome-angular2#92]
Hi Patrick...

Added two resources around testing. I see the help_out monicker afterward, but it seems to keep it on the same line. Do you want that help out link moved down further?  I don't want to commit anything else before you decide what to do - see the Test resources and the help_out link after my two blog entries.

Thanks and great resource!!

Ken

**Comment by rolandjitsu** [comment]
Is this still an issue?

**Comment by rolandjitsu** [comment]
Closing this as no answer in more than 2 weeks.
